name: site
on:
  push:
    branches: [main]

jobs:
  release:
    name: docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Set up Github Workspace
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: install-dependencies
        run: npm ci
      - name: build-site
        run: npm run build
      - name: github-pages
        uses: juftin/actions/github-pages@v1
        id: deployment
        with:
          path: dist
